#!/bin/bash

# port esp32 is connected to
PORT=/dev/ttyUSB0

# baud rate for programming
FLASH_BAUDRATE=115200

# baud rate for terminal
TERM_BAUDRATE=115200

# Flash Mode
FLASH_MODE="dio"

# Flash Speed
FLASH_SPEED="40m"

# Use bootloader (needed for using irom, drom and psram)
USE_BOOTLOADER=1

# debug or release build
TYPE=debug

# address of partition table
PARTION_ADDR=0x8000

# address of application
APP_ADDR=0x10000

#source of the utility to generate the binary partition table
GENPART_SOURCE=https://github.com/espressif/esp-idf/blob/v4.0/components/partition_table/gen_esp32part.py?raw=true

# source of the bootloader
# customized bootloader which initializes the external psram
BOOTLOADER_SOURCE=https://github.com/arjanmels/esp32_bootloader_init_extram/blob/v1.0/build/bootloader/bootloader.bin?raw=true
# default bootloader from the espressif arduino github
#BOOTLOADER_SOURCE=https://github.com/espressif/arduino-esp32/blob/idf-release/v4.0/tools/sdk/bin/bootloader_dio_40m.bin?raw=true


# set to build example
EXAMPLE=""


showhelp() {
cat << EOF
Usage: flash -hrtb -p <serial port> <example>

-h, --help                      Display Help
-r, --release                   Build in release mode
-p, --port <serial port>        Set serial port (default: $PORT)
-b, --baudrate <baudrate>       Set baudrate for flasing (default: $FLASH_BAUDRATE)
  , --termbaudrate <baudrate>   Set baudrate for monitoring (default: $TERM_BAUDRATE)
-t, --terminal                  Open terminal program after flashing
-e, --example <example>         Build the specified example
EOF
}

# get command line options
options=$(getopt -l "help,release,port:,terminal,baudrate:,termbaudrate:,example:" -o "hrp:tb:e:" -a -- "$@")

if [ $? -ne 0 ]; then
    echo
    showhelp
    exit 1
fi

eval set -- "$options"


while true
do
    case $1 in
    -h|--help)
        showhelp
        exit 0
        ;;
    -r|--release)
        export TYPE=release
        ;;
    -p|--port)
        shift
        export PORT=$1
        ;;
    -t|--terminal)
        export TERMINAL=1
        ;;
    -b|--baudrate)
        shift
        export FLASH_BAUDRATE=$1
        ;;
    --termbaudrate)
        shift
        export TERM_BAUDRATE=$1
        ;;
    -e|--example)
        shift
        export EXAMPLE=$1
        ;;
    --)
        shift
        break;;
    esac
shift
done

if [[ $# -ne 0 ]] ;
then
    echo "*** Wrong number of arguments" >&2
    echo
    showhelp
    exit 1
fi

if [[ ! -f Cargo.toml ]] ;
then
    echo "*** Must be run in root of project where Cargo.toml file is located" >&2
    exit 1
fi

if [ -z "$EXAMPLE" ]; then
    FILE=$(awk 'BEGIN {FS="[ \t=\"]+";} /^\s*\[/ {section=$1} tolower(section)=="[package]" && tolower($0) ~ /^\s*name/ {print $2}' Cargo.toml)
    BIN_PATH=target/xtensa-esp32-none-elf/$TYPE/$FILE
    EXAMPLE_ARG=""
else 
    BIN_PATH=target/xtensa-esp32-none-elf/$TYPE/examples/$EXAMPLE
    EXAMPLE_ARG="--example "$EXAMPLE
fi

# build the specific example
if [ "$TYPE" = "release" ]
then 
    cargo xbuild --release $EXAMPLE_ARG
else
    cargo xbuild $EXAMPLE_ARG
fi

# if cargo returned an error quit the script
if [ $? -ne 0 ]; then
    exit 1
fi

#display section sizes
echo
xtensa-esp32-elf-readelf $BIN_PATH -S|egrep 'BIT|\[Nr\]' |awk 'BEGIN {FS="[ \t\[\]]+"}  $9~/A|Flg/ {size=sprintf("%7d", "0x" $7)+0; printf("%-3s %-20s %-8s %-8s %-8s %8s %-3s %-3s\n",$2,$3,$4,$5,$7,((size>0)?size:$7),$9,$12); total+=size; } END { printf("\nTotal: %d bytes\n",total)}'
echo

# convert to bin
rm $BIN_PATH.bin 2>/dev/null
esptool.py --chip esp32 elf2image --flash_mode=$FLASH_MODE --flash_freq $FLASH_SPEED  -o $BIN_PATH.bin $BIN_PATH
esptool.py --chip esp32 image_info $BIN_PATH.bin
echo

if [ $? -ne 0 ]; then
    exit 1
fi

# kill terminal programs using the same port
ps -ef|grep $PORT|egrep -v "$0|grep" |awk '{print $2}'|xargs -r kill

if [[ !USE_BOOTLOADER -eq 1 ]] ; then
    esptool.py --chip esp32 --port $PORT --baud $FLASH_BAUDRATE --before default_reset --after hard_reset write_flash --flash_mode=$FLASH_MODE --flash_freq $FLASH_SPEED --flash_size detect 0x1000 $BIN_PATH.bin
else
    # get gen_esp32part.py and create binary partition table
    curl -s -S -L $GENPART_SOURCE --output target/gen_esp32part.py
    
    rm target/partitions.bin 2> /dev/null
    python target/gen_esp32part.py partitions.csv target/partitions.bin 

    # get bootloader.bin file (from arduino-esp32 repository)
    # (different variants exist, but only difference is flash settings which are overriden by esptool)
    curl -s -S -L $BOOTLOADER_SOURCE --output target/bootloader.bin

    # check if bootloader.bin and paritions.bin are already correctly flashed (to prevent unneceesary writes)
    esptool.py --chip esp32 --port $PORT --baud $FLASH_BAUDRATE --before default_reset --after hard_reset verify_flash --flash_mode=$FLASH_MODE --flash_freq $FLASH_SPEED --flash_size detect 0x1000 target/bootloader.bin $PARTION_ADDR target/partitions.bin
    if [ $? -ne 0 ]; then
        # flash bootloader.bin, partitions.bin and application
        esptool.py --chip esp32 --port $PORT --baud $FLASH_BAUDRATE --before default_reset --after hard_reset write_flash --flash_mode=$FLASH_MODE --flash_freq $FLASH_SPEED --flash_size detect 0x1000 target/bootloader.bin $PARTION_ADDR target/partitions.bin $APP_ADDR $BIN_PATH.bin
    else
        # flash application only
        esptool.py --chip esp32 --port $PORT --baud $FLASH_BAUDRATE --before default_reset --after hard_reset write_flash --flash_mode=$FLASH_MODE --flash_freq $FLASH_SPEED --flash_size detect $APP_ADDR $BIN_PATH.bin
    fi
fi


# start terminal program
if [[ TERMINAL -eq 1 ]]
then
    echo
    echo "Starting terminal"
    gnome-terminal --geometry 200x15+0+2000 -- picocom -b $TERM_BAUDRATE $PORT --imap lfcrlf 2>/dev/null
fi